logging:
    level:
        root: DEBUG
spring:
    cloud:
        config:
            discovery:
                enabled: false
            enabled: false
        discovery:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
